version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nola_backend
    ports:
      - "${PORT:-8080}:8080"
    environment:
      NODE_ENV: development
      # Agrega aquí otras variables de entorno necesarias para tu app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: nola_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nola_redis
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  pgdata:
  redisdata: